/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/kits/Animation.vue')['default']
    Audio: typeof import('./src/components/kits/Audio.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    CustomCursor: typeof import('./src/components/kits/CustomCursor.vue')['default']
    FullscreenTrigger: typeof import('./src/components/kits/FullscreenTrigger.vue')['default']
    GithubIcon: typeof import('./src/components/kits/GithubIcon.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategory: typeof import('./src/components/SubCategory.vue')['default']
  }
}
