/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/kits/Animation.vue')['default']
    Audio: typeof import('./src/components/kits/Audio.vue')['default']
    Button: typeof import('./src/components/kits/Button.vue')['default']
    Category: typeof import('./src/components/category/Category.vue')['default']
    CustomCursor: typeof import('./src/components/kits/CustomCursor.vue')['default']
    FullscreenTrigger: typeof import('./src/components/kits/FullscreenTrigger.vue')['default']
    GithubIcon: typeof import('./src/components/kits/GithubIcon.vue')['default']
    Info: typeof import('./src/components/kits/Info.vue')['default']
    Item: typeof import('./src/components/category/Item.vue')['default']
    Links: typeof import('./src/components/kits/Links.vue')['default']
    MenuBar: typeof import('./src/components/kits/menu/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/kits/menu/MenuItem.vue')['default']
    Modal: typeof import('./src/components/kits/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategory: typeof import('./src/components/category/SubCategory.vue')['default']
    Title: typeof import('./src/components/kits/Title.vue')['default']
  }
}
